FROM registry.access.redhat.com/ubi9/ubi-minimal:latest
ARG MODEL=RedHatAI/Llama-3.3-70B-Instruct-speculator.eagle3 \
    NAME=redhatai--llama-3_3-70b-instruct-speculator_eagle3 \
    REF=main

COPY eagle3.py /models/
COPY generation_config.json /models/
COPY README.md /models/
COPY config.json /models/
COPY model.safetensors /models/

COPY README.md /modelcard.md

LABEL \
    name=${NAME}-modelcar \
    io.k8s.display-name=${NAME}-modelcar \
    description="A very small RHEL image which contains the contents of huggingface.co/${MODEL} downloaded to /models" \
    io.k8s.description="A very small RHEL image which contains the contents of huggingface.co/${MODEL} downloaded to /models" \
    maintainer="James Harmison <jharmiso@redhat.com>" \
    release=1 \
    summary="${MODEL} model car image" \
    url="https://github.com/jharmison-redhat/modelcar-maker" \
    vcs-ref="${REF}"