models:
  - repo: TinyLlama/TinyLlama-1.1B-Chat-v1.0
modelcar:
  image:
    registry: quay.io
    repository: jharmison/models
  imageStream:
    create: false
  dockerConfigJson: |
    {
      "auths": {
        "quay.io": {
          "auth": "ZmFrZXVzZXI6ZmFrZXBhc3N3b3Jk"
        }
      }
    }
