nameOverride: ""
fullnameOverride: ""

huggingFace:
  token: "" # recommended even for public models, to raise rate limits

image:
  registry: ghcr.io
  repository: jharmison-redhat/modelcar-maker
  tag: "" # defaults to Chart AppVersion
  manifestHash: "" # to pin to a specific manifest hash (optional)
  pullPolicy: IfNotPresent

# Integer between 0 and 3 (higher works, does not matter)
verbosity: 0

models: [] # array of Hugging Face repo IDs, modelcar-maker settings for each model, etc.
# - repo: unsloth/Qwen3.5-9B-MTP-GGUF
#   files:
#     - README.md
#     - Qwen3.5-9B-Q4_K_S.gguf
#   tag: unsloth--qwen3_5-9b-q4_k_s-modelcar

modelcar:
  image:
    registry: image-registry.openshift-image-registry.svc:5000
    repository: '{{ .Release.Namespace }}/{{ include "modelcar-maker.image-stream-name" . }}' # value here is rendered, so helm syntax ok
  imageStream:
    create: true # recommended if using internal registry, we bind RBAC to support our ServiceAccount on this flag also
    name: ""
    groups: # list of OpenShift Groups to be authorized to pull the model (this allows pulls from any namespace or user by default)
      - system:authenticated
  dockerConfigJson: "" # Set to a real, skopeo-format config.json text to support pulling the base image(if you change it) and pushing the modelcar image (if not using an ImageStream)
  skipIfExists: true # set to false to update modelcars whenever job runs
  baseImage: registry.access.redhat.com/ubi10/ubi-micro:10.2
  baseImagePull: true # especially important to be true if using a PVC workspace
  cleanup: true # cleanup happens between models, so for many models this helps (but is pointless with few/small)
  maintainer: James Harmison <jharmiso@redhat.com>

dataScienceConnections: # for use with OpenShift AI Model Serving
  create: true
  namespace: "" # defaults to the chart release namespace

imagePuller:
  create: false
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 100%
  nodeSelector: {}

workspace:
  type: emptyDir # one of emptyDir or pvc
  emptyDir: {} # you can set limits to prevent disk pressure if it's an issue
  pvc: # workspace persistence means you can save models and images in the PVC across runs
    size: 100Gi # make sure this is big enough for two copies of your models, with some room to spare (use cleanup to help some)
    storageClassName: ""
    accessModes:
      - ReadWriteOnce
  modelCleanup: true # cleanup happens between models, so for many models this helps (but is pointless with few/small)

backoffLimit: 4
podSecurityContext:
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault
securityContext:
  capabilities:
    drop:
      - ALL
resources: {}
podAnnotations: {}

serviceAccount:
  create: true
  name: ""
