FROM registry.access.redhat.com/ubi9/ubi-minimal:latest


COPY README.md /models/
COPY config.json /models/
COPY generation_config.json /models/
COPY latest /models/
COPY merges.txt /models/
COPY model-00001-of-00006.safetensors /models/
COPY model-00002-of-00006.safetensors /models/
COPY model-00003-of-00006.safetensors /models/
COPY model-00004-of-00006.safetensors /models/
COPY model-00005-of-00006.safetensors /models/
COPY model-00006-of-00006.safetensors /models/
COPY model.safetensors.index.json /models/
COPY scheduler.pt /models/
COPY special_tokens_map.json /models/
COPY tokenizer.json /models/
COPY tokenizer_config.json /models/
COPY trainer_state.json /models/
COPY training_args.bin /models/
COPY vocab.json /models/
COPY zero_to_fp32.py /models/

COPY README.md /modelcard.md

LABEL \
    name=openmeditron--meditron3-phi4-14b-modelcar \
    io.k8s.display-name=openmeditron--meditron3-phi4-14b-modelcar \
    description="A very small RHEL image which contains the contents of huggingface.co/OpenMeditron/Meditron3-Phi4-14B downloaded to /models" \
    io.k8s.description="A very small RHEL image which contains the contents of huggingface.co/OpenMeditron/Meditron3-Phi4-14B downloaded to /models" \
    maintainer="James Harmison <jharmiso@redhat.com>" \
    release=1 \
    summary="OpenMeditron/Meditron3-Phi4-14B model car image" \
    url="https://github.com/jharmison-redhat/modelcar-maker" \
    model.name="OpenMeditron/Meditron3-Phi4-14B" \
    model.commit="9b865e2044635e4604409e2f5e51ec55f946d040"