FROM registry.access.redhat.com/ubi9/ubi-minimal:latest


COPY 1_Pooling /models/
COPY README.md /models/
COPY config.json /models/
COPY config_sentence_transformers.json /models/
COPY model.safetensors /models/
COPY modules.json /models/
COPY onnx /models/
COPY sentence_xlm-roberta_config.json /models/
COPY sentencepiece.bpe.model /models/
COPY special_tokens_map.json /models/
COPY tokenizer.json /models/
COPY tokenizer_config.json /models/

COPY README.md /modelcard.md

LABEL \
    name=intfloat--multilingual-e5-large-instruct-modelcar \
    io.k8s.display-name=intfloat--multilingual-e5-large-instruct-modelcar \
    description="A very small RHEL image which contains the contents of huggingface.co/intfloat/multilingual-e5-large-instruct downloaded to /models" \
    io.k8s.description="A very small RHEL image which contains the contents of huggingface.co/intfloat/multilingual-e5-large-instruct downloaded to /models" \
    maintainer="James Harmison <jharmiso@redhat.com>" \
    release=1 \
    summary="intfloat/multilingual-e5-large-instruct model car image" \
    url="https://github.com/jharmison-redhat/modelcar-maker" \
    model.name="intfloat/multilingual-e5-large-instruct" \
    model.commit="274baa43b0e13e37fafa6428dbc7938e62e5c439"