FROM registry.access.redhat.com/ubi9/ubi-minimal:latest


COPY README.md /models/
COPY chat_template.jinja /models/
COPY config.json /models/
COPY generation_config.json /models/
COPY merges.txt /models/
COPY model-00001-of-00014.safetensors /models/
COPY model-00002-of-00014.safetensors /models/
COPY model-00003-of-00014.safetensors /models/
COPY model-00004-of-00014.safetensors /models/
COPY model-00005-of-00014.safetensors /models/
COPY model-00006-of-00014.safetensors /models/
COPY model-00007-of-00014.safetensors /models/
COPY model-00008-of-00014.safetensors /models/
COPY model-00009-of-00014.safetensors /models/
COPY model-00010-of-00014.safetensors /models/
COPY model-00011-of-00014.safetensors /models/
COPY model-00012-of-00014.safetensors /models/
COPY model-00013-of-00014.safetensors /models/
COPY model-00014-of-00014.safetensors /models/
COPY model.safetensors.index.json /models/
COPY model.sig /models/
COPY special_tokens_map.json /models/
COPY tokenizer.json /models/
COPY tokenizer_config.json /models/
COPY vocab.json /models/

COPY README.md /modelcard.md

LABEL \
    name=ibm-granite--granite-4_0-h-small-modelcar \
    io.k8s.display-name=ibm-granite--granite-4_0-h-small-modelcar \
    description="A very small RHEL image which contains the contents of huggingface.co/ibm-granite/granite-4.0-h-small downloaded to /models" \
    io.k8s.description="A very small RHEL image which contains the contents of huggingface.co/ibm-granite/granite-4.0-h-small downloaded to /models" \
    maintainer="James Harmison <jharmiso@redhat.com>" \
    release=1 \
    summary="ibm-granite/granite-4.0-h-small model car image" \
    url="https://github.com/jharmison-redhat/modelcar-maker" \
    model.name="ibm-granite/granite-4.0-h-small" \
    model.commit="ba01e5b3c048c6a827b8d26551a974b405110a15"