FROM registry.access.redhat.com/ubi9/ubi-minimal:latest
ARG MODEL=BAAI/bge-m3 \
    NAME=baai--bge-m3 \
    REF=main

COPY imgs /models/
COPY 1_Pooling /models/
COPY config.json /models/
COPY config_sentence_transformers.json /models/
COPY README.md /models/
COPY onnx /models/
COPY modules.json /models/
COPY long.jpg /models/
COPY colbert_linear.pt /models/
COPY sentence_bert_config.json /models/
COPY sparse_linear.pt /models/
COPY special_tokens_map.json /models/
COPY tokenizer_config.json /models/
COPY tokenizer.json /models/
COPY sentencepiece.bpe.model /models/
COPY pytorch_model.bin /models/

COPY README.md /modelcard.md

LABEL \
    name=${NAME}-modelcar \
    io.k8s.display-name=${NAME}-modelcar \
    description="A very small RHEL image which contains ${MODEL} downloaded to /models" \
    io.k8s.description="A very small RHEL image which contains ${MODEL} downloaded to /models" \
    maintainer="James Harmison <jharmiso@redhat.com>" \
    release=1 \
    summary="${MODEL} model car image" \
    url="https://github.com/jharmison-redhat/modelcar-maker" \
    vcs-ref="${REF}"