FROM registry.access.redhat.com/ubi9/ubi-minimal:latest


COPY README.md /models/
COPY config.json /models/
COPY generation_config.json /models/
COPY model-00001-of-00008.safetensors /models/
COPY model-00002-of-00008.safetensors /models/
COPY model-00003-of-00008.safetensors /models/
COPY model-00004-of-00008.safetensors /models/
COPY model-00005-of-00008.safetensors /models/
COPY model-00006-of-00008.safetensors /models/
COPY model-00007-of-00008.safetensors /models/
COPY model-00008-of-00008.safetensors /models/
COPY model.safetensors.index.json /models/
COPY recipe.yaml /models/
COPY special_tokens_map.json /models/
COPY tokenizer.json /models/
COPY tokenizer_config.json /models/

COPY README.md /modelcard.md

LABEL \
    name=redhatai--llama-3_3-70b-instruct-quantized_w4a16-modelcar \
    io.k8s.display-name=redhatai--llama-3_3-70b-instruct-quantized_w4a16-modelcar \
    description="A very small RHEL image which contains the contents of huggingface.co/RedHatAI/Llama-3.3-70B-Instruct-quantized.w4a16 downloaded to /models" \
    io.k8s.description="A very small RHEL image which contains the contents of huggingface.co/RedHatAI/Llama-3.3-70B-Instruct-quantized.w4a16 downloaded to /models" \
    maintainer="James Harmison <jharmiso@redhat.com>" \
    release=1 \
    summary="RedHatAI/Llama-3.3-70B-Instruct-quantized.w4a16 model car image" \
    url="https://github.com/jharmison-redhat/modelcar-maker" \
    model.name="RedHatAI/Llama-3.3-70B-Instruct-quantized.w4a16" \
    model.commit="c862528b57a16c7bf5bfa2c3b04a6134bb901bb5"