FROM registry.access.redhat.com/ubi9/ubi-minimal:latest
ARG MODEL=RedHatAI/Llama-3.3-70B-Instruct-quantized.w4a16 \
    NAME=redhatai--llama-3_3-70b-instruct-quantized_w4a16 \
    REF=main

COPY README.md /models/
COPY generation_config.json /models/
COPY config.json /models/
COPY model-00003-of-00008.safetensors /models/
COPY model.safetensors.index.json /models/
COPY recipe.yaml /models/
COPY special_tokens_map.json /models/
COPY model-00006-of-00008.safetensors /models/
COPY tokenizer_config.json /models/
COPY model-00002-of-00008.safetensors /models/
COPY model-00004-of-00008.safetensors /models/
COPY model-00007-of-00008.safetensors /models/
COPY model-00008-of-00008.safetensors /models/
COPY tokenizer.json /models/
COPY model-00001-of-00008.safetensors /models/
COPY model-00005-of-00008.safetensors /models/

COPY README.md /modelcard.md

LABEL \
    name=${NAME}-modelcar \
    io.k8s.display-name=${NAME}-modelcar \
    description="A very small RHEL image which contains the contents of huggingface.co/${MODEL} downloaded to /models" \
    io.k8s.description="A very small RHEL image which contains the contents of huggingface.co/${MODEL} downloaded to /models" \
    maintainer="James Harmison <jharmiso@redhat.com>" \
    release=1 \
    summary="${MODEL} model car image" \
    url="https://github.com/jharmison-redhat/modelcar-maker" \
    vcs-ref="${REF}"