FROM registry.access.redhat.com/ubi9/ubi-minimal:latest
ARG MODEL=meta-llama/Llama-3.3-70B-Instruct \
    NAME=meta-llama--llama-3_3-70b-instruct \
    REF=main

COPY config.json /models/
COPY generation_config.json /models/
COPY USE_POLICY.md /models/
COPY LICENSE /models/
COPY README.md /models/
COPY model-00002-of-00030.safetensors /models/
COPY model-00006-of-00030.safetensors /models/
COPY model-00003-of-00030.safetensors /models/
COPY model-00004-of-00030.safetensors /models/
COPY model-00008-of-00030.safetensors /models/
COPY model-00001-of-00030.safetensors /models/
COPY model-00007-of-00030.safetensors /models/
COPY model-00005-of-00030.safetensors /models/
COPY model-00009-of-00030.safetensors /models/
COPY model-00011-of-00030.safetensors /models/
COPY model-00010-of-00030.safetensors /models/
COPY model-00015-of-00030.safetensors /models/
COPY model-00012-of-00030.safetensors /models/
COPY model-00013-of-00030.safetensors /models/
COPY model-00014-of-00030.safetensors /models/
COPY model-00016-of-00030.safetensors /models/
COPY model-00017-of-00030.safetensors /models/
COPY model-00018-of-00030.safetensors /models/
COPY model-00019-of-00030.safetensors /models/
COPY model-00020-of-00030.safetensors /models/
COPY model-00021-of-00030.safetensors /models/
COPY model-00022-of-00030.safetensors /models/
COPY model-00023-of-00030.safetensors /models/
COPY model.safetensors.index.json /models/
COPY model-00024-of-00030.safetensors /models/
COPY model-00025-of-00030.safetensors /models/
COPY model-00027-of-00030.safetensors /models/
COPY model-00026-of-00030.safetensors /models/
COPY model-00028-of-00030.safetensors /models/
COPY model-00030-of-00030.safetensors /models/
COPY model-00029-of-00030.safetensors /models/
COPY special_tokens_map.json /models/
COPY tokenizer.json /models/
COPY tokenizer_config.json /models/

COPY README.md /modelcard.md

LABEL \
    name=${NAME}-modelcar \
    io.k8s.display-name=${NAME}-modelcar \
    description="A very small RHEL image which contains ${MODEL} downloaded to /models" \
    io.k8s.description="A very small RHEL image which contains ${MODEL} downloaded to /models" \
    maintainer="James Harmison <jharmiso@redhat.com>" \
    release=1 \
    summary="${MODEL} model car image" \
    url="https://github.com/jharmison-redhat/modelcar-maker" \
    vcs-ref="${REF}"