FROM registry.access.redhat.com/ubi9/ubi-minimal:latest


COPY LICENSE /models/
COPY README.md /models/
COPY USE_POLICY.md /models/
COPY config.json /models/
COPY generation_config.json /models/
COPY model-00001-of-00030.safetensors /models/
COPY model-00002-of-00030.safetensors /models/
COPY model-00003-of-00030.safetensors /models/
COPY model-00004-of-00030.safetensors /models/
COPY model-00005-of-00030.safetensors /models/
COPY model-00006-of-00030.safetensors /models/
COPY model-00007-of-00030.safetensors /models/
COPY model-00008-of-00030.safetensors /models/
COPY model-00009-of-00030.safetensors /models/
COPY model-00010-of-00030.safetensors /models/
COPY model-00011-of-00030.safetensors /models/
COPY model-00012-of-00030.safetensors /models/
COPY model-00013-of-00030.safetensors /models/
COPY model-00014-of-00030.safetensors /models/
COPY model-00015-of-00030.safetensors /models/
COPY model-00016-of-00030.safetensors /models/
COPY model-00017-of-00030.safetensors /models/
COPY model-00018-of-00030.safetensors /models/
COPY model-00019-of-00030.safetensors /models/
COPY model-00020-of-00030.safetensors /models/
COPY model-00021-of-00030.safetensors /models/
COPY model-00022-of-00030.safetensors /models/
COPY model-00023-of-00030.safetensors /models/
COPY model-00024-of-00030.safetensors /models/
COPY model-00025-of-00030.safetensors /models/
COPY model-00026-of-00030.safetensors /models/
COPY model-00027-of-00030.safetensors /models/
COPY model-00028-of-00030.safetensors /models/
COPY model-00029-of-00030.safetensors /models/
COPY model-00030-of-00030.safetensors /models/
COPY model.safetensors.index.json /models/
COPY special_tokens_map.json /models/
COPY tokenizer.json /models/
COPY tokenizer_config.json /models/

COPY README.md /modelcard.md

LABEL \
    name=meta-llama--llama-3_3-70b-instruct-modelcar \
    io.k8s.display-name=meta-llama--llama-3_3-70b-instruct-modelcar \
    description="A very small RHEL image which contains the contents of huggingface.co/meta-llama/Llama-3.3-70B-Instruct downloaded to /models" \
    io.k8s.description="A very small RHEL image which contains the contents of huggingface.co/meta-llama/Llama-3.3-70B-Instruct downloaded to /models" \
    maintainer="James Harmison <jharmiso@redhat.com>" \
    release=1 \
    summary="meta-llama/Llama-3.3-70B-Instruct model car image" \
    url="https://github.com/jharmison-redhat/modelcar-maker" \
    model.name="meta-llama/Llama-3.3-70B-Instruct" \
    model.commit="6f6073b423013f6a7d4d9f39144961bfbfbc386b"