FROM registry.access.redhat.com/ubi9/ubi-minimal:latest


COPY README.md /models/
COPY config.json /models/
COPY generation_config.json /models/
COPY model.safetensors /models/
COPY recipe.yaml /models/
COPY special_tokens_map.json /models/
COPY tokenizer.json /models/
COPY tokenizer_config.json /models/

COPY README.md /modelcard.md

LABEL \
    name=redhatai--llama-3_2-3b-instruct-fp8-modelcar \
    io.k8s.display-name=redhatai--llama-3_2-3b-instruct-fp8-modelcar \
    description="A very small RHEL image which contains the contents of huggingface.co/RedHatAI/Llama-3.2-3B-Instruct-FP8 downloaded to /models" \
    io.k8s.description="A very small RHEL image which contains the contents of huggingface.co/RedHatAI/Llama-3.2-3B-Instruct-FP8 downloaded to /models" \
    maintainer="James Harmison <jharmiso@redhat.com>" \
    release=1 \
    summary="RedHatAI/Llama-3.2-3B-Instruct-FP8 model car image" \
    url="https://github.com/jharmison-redhat/modelcar-maker" \
    model.name="RedHatAI/Llama-3.2-3B-Instruct-FP8" \
    model.commit="777080db317da2ba578849705baded76849088fa"