[meta]
verbosity = 0

[image]
registry = "quay.io"
repository = "jharmison/models"
push = true
cleanup = false
skip_if_exists = true

[models]
cleanup = false
default = [
    "RedHatAI/granite-3.1-8b-instruct-quantized.w8a8",
    "ibm-granite/granite-3.2-8b-instruct",
    "ibm-granite/granite-3.3-8b-instruct",
    "ibm-granite/granite-4.0-tiny-preview",
    "mistralai/Mistral-Small-3.1-24B-Instruct-2503",
    "RedHatAI/Mistral-Small-3.1-24B-Instruct-2503-FP8-dynamic",
    "meta-llama/Llama-3.2-3B-Instruct",
    "meta-llama/Llama-3.3-70B-Instruct",
    "RedHatAI/Llama-3.2-3B-Instruct-quantized.w8a8",
    "RedHatAI/Llama-3.2-3B-Instruct-FP8",
    "RedHatAI/Llama-3.3-70B-Instruct-quantized.w4a16",
    "Qwen/Qwen3-8B",
    "Qwen/Qwen3-14B",
    "Qwen/Qwen3-14B-FP8",
    "Qwen/Qwen3-8B-FP8",
    "intfloat/multilingual-e5-large-instruct",
    "intfloat/multilingual-e5-large",
    "BAAI/bge-m3",
    "ibm-granite/granite-8b-code-instruct-128k",
]
