[meta]
verbosity = 0

[image]
registry = "quay.io"
repository = "jharmison/models"
base_image = "registry.access.redhat.com/ubi10/ubi-micro:10.2"
push = true
cleanup = false
skip_if_exists = true
pull = true

[image.labels]
name = "{tag}"
"io.k8s.display-name" = "{tag}"
description = "A very small RHEL image which contains the contents of huggingface.co/{repo_id} downloaded to /models"
"io.k8s.description" = "A very small RHEL image which contains the contents of huggingface.co/{repo_id} downloaded to /models"
maintainer = "James Harmison <jharmiso@redhat.com>"
release = "1"
summary = "{repo_id} model car image"
url = "https://github.com/jharmison-redhat/modelcar-maker"
"model.name" = "{repo_id}"
"model.commit" = "{commit}"

[image.annotations]
"org.opencontainers.image.source" = "https://github.com/jharmison-redhat/modelcar-maker"

[models]
cleanup = false
default = []
