[meta]
verbosity = 0

[image]
registry = "quay.io"
repository = "jharmison/models"
base_image = "registry.access.redhat.com/ubi10/ubi-micro:10.2"
backend = "olot"
architectures = ["amd64", "arm64"]
push = true
cleanup = false
skip_if_exists = true
pull = true

[models]
cleanup = false
default = []
