FROM registry.access.redhat.com/ubi9/ubi-minimal:latest


COPY LICENSE /models/
COPY README.md /models/
COPY USAGE_POLICY /models/
COPY chat_template.jinja /models/
COPY config.json /models/
COPY generation_config.json /models/
COPY metal /models/
COPY model-00000-of-00002.safetensors /models/
COPY model-00001-of-00002.safetensors /models/
COPY model-00002-of-00002.safetensors /models/
COPY model.safetensors.index.json /models/
COPY special_tokens_map.json /models/
COPY tokenizer.json /models/
COPY tokenizer_config.json /models/

COPY README.md /modelcard.md

LABEL \
    name=redhatai--gpt-oss-20b-modelcar \
    io.k8s.display-name=redhatai--gpt-oss-20b-modelcar \
    description="A very small RHEL image which contains the contents of huggingface.co/RedHatAI/gpt-oss-20b downloaded to /models" \
    io.k8s.description="A very small RHEL image which contains the contents of huggingface.co/RedHatAI/gpt-oss-20b downloaded to /models" \
    maintainer="James Harmison <jharmiso@redhat.com>" \
    release=1 \
    summary="RedHatAI/gpt-oss-20b model car image" \
    url="https://github.com/jharmison-redhat/modelcar-maker" \
    model.name="RedHatAI/gpt-oss-20b" \
    model.commit="b9af430f9facbe096af104e8292f90ed16809973"