FROM registry.access.redhat.com/ubi9/ubi-minimal:latest


COPY README.md /models/
COPY added_tokens.json /models/
COPY config.json /models/
COPY generation_config.json /models/
COPY merges.txt /models/
COPY model-00001-of-00004.safetensors /models/
COPY model-00002-of-00004.safetensors /models/
COPY model-00003-of-00004.safetensors /models/
COPY model-00004-of-00004.safetensors /models/
COPY model.safetensors.index.json /models/
COPY special_tokens_map.json /models/
COPY tokenizer.json /models/
COPY tokenizer_config.json /models/
COPY vocab.json /models/

COPY README.md /modelcard.md

LABEL \
    name=ibm-granite--granite-3_2-8b-instruct-modelcar \
    io.k8s.display-name=ibm-granite--granite-3_2-8b-instruct-modelcar \
    description="A very small RHEL image which contains the contents of huggingface.co/ibm-granite/granite-3.2-8b-instruct downloaded to /models" \
    io.k8s.description="A very small RHEL image which contains the contents of huggingface.co/ibm-granite/granite-3.2-8b-instruct downloaded to /models" \
    maintainer="James Harmison <jharmiso@redhat.com>" \
    release=1 \
    summary="ibm-granite/granite-3.2-8b-instruct model car image" \
    url="https://github.com/jharmison-redhat/modelcar-maker" \
    model.name="ibm-granite/granite-3.2-8b-instruct" \
    model.commit="610d8c6ee9c84ce51f6dfd7bc5c0215d95d49695"