FROM registry.access.redhat.com/ubi9/ubi-minimal:latest
ARG MODEL=meta-llama/Llama-3.2-3B-Instruct \
    NAME=meta-llama--llama-3_2-3b-instruct \
    REF=main

COPY LICENSE.txt /models/
COPY USE_POLICY.md /models/
COPY original /models/
COPY README.md /models/
COPY config.json /models/
COPY generation_config.json /models/
COPY model.safetensors.index.json /models/
COPY special_tokens_map.json /models/
COPY tokenizer_config.json /models/
COPY tokenizer.json /models/
COPY model-00002-of-00002.safetensors /models/
COPY model-00001-of-00002.safetensors /models/

COPY README.md /modelcard.md

LABEL \
    name=${NAME}-modelcar \
    io.k8s.display-name=${NAME}-modelcar \
    description="A very small RHEL image which contains ${MODEL} downloaded to /models" \
    io.k8s.description="A very small RHEL image which contains ${MODEL} downloaded to /models" \
    maintainer="James Harmison <jharmiso@redhat.com>" \
    release=1 \
    summary="${MODEL} model car image" \
    url="https://github.com/jharmison-redhat/modelcar-maker" \
    vcs-ref="${REF}"