FROM registry.access.redhat.com/ubi9/ubi-minimal:latest


COPY LICENSE /models/
COPY README.md /models/
COPY config.json /models/
COPY config_1m.json /models/
COPY generation_config.json /models/
COPY merges.txt /models/
COPY model-00001-of-00016.safetensors /models/
COPY model-00002-of-00016.safetensors /models/
COPY model-00003-of-00016.safetensors /models/
COPY model-00004-of-00016.safetensors /models/
COPY model-00005-of-00016.safetensors /models/
COPY model-00006-of-00016.safetensors /models/
COPY model-00007-of-00016.safetensors /models/
COPY model-00008-of-00016.safetensors /models/
COPY model-00009-of-00016.safetensors /models/
COPY model-00010-of-00016.safetensors /models/
COPY model-00011-of-00016.safetensors /models/
COPY model-00012-of-00016.safetensors /models/
COPY model-00013-of-00016.safetensors /models/
COPY model-00014-of-00016.safetensors /models/
COPY model-00015-of-00016.safetensors /models/
COPY model-00016-of-00016.safetensors /models/
COPY model.safetensors.index.json /models/
COPY tokenizer.json /models/
COPY tokenizer_config.json /models/
COPY vocab.json /models/

COPY README.md /modelcard.md

LABEL \
    name=qwen--qwen3-30b-a3b-thinking-2507-modelcar \
    io.k8s.display-name=qwen--qwen3-30b-a3b-thinking-2507-modelcar \
    description="A very small RHEL image which contains the contents of huggingface.co/Qwen/Qwen3-30B-A3B-Thinking-2507 downloaded to /models" \
    io.k8s.description="A very small RHEL image which contains the contents of huggingface.co/Qwen/Qwen3-30B-A3B-Thinking-2507 downloaded to /models" \
    maintainer="James Harmison <jharmiso@redhat.com>" \
    release=1 \
    summary="Qwen/Qwen3-30B-A3B-Thinking-2507 model car image" \
    url="https://github.com/jharmison-redhat/modelcar-maker" \
    model.name="Qwen/Qwen3-30B-A3B-Thinking-2507" \
    model.commit="144afc2f379b542fdd4e85a1fcd5e1f79112d95d"