FROM registry.access.redhat.com/ubi9/ubi-minimal:latest


COPY README.md /models/
COPY config.json /models/
COPY convert_voxtral_hf_to_mistral.py /models/
COPY generation_config.json /models/
COPY model-00001-of-00002.safetensors /models/
COPY model-00002-of-00002.safetensors /models/
COPY model.safetensors.index.json /models/
COPY params.json /models/
COPY preprocessor_config.json /models/
COPY recipe.yaml /models/
COPY tekken.json /models/

COPY README.md /modelcard.md

LABEL \
    name=redhatai--voxtral-mini-3b-2507-fp8-dynamic-modelcar \
    io.k8s.display-name=redhatai--voxtral-mini-3b-2507-fp8-dynamic-modelcar \
    description="A very small RHEL image which contains the contents of huggingface.co/RedHatAI/Voxtral-Mini-3B-2507-FP8-dynamic downloaded to /models" \
    io.k8s.description="A very small RHEL image which contains the contents of huggingface.co/RedHatAI/Voxtral-Mini-3B-2507-FP8-dynamic downloaded to /models" \
    maintainer="James Harmison <jharmiso@redhat.com>" \
    release=1 \
    summary="RedHatAI/Voxtral-Mini-3B-2507-FP8-dynamic model car image" \
    url="https://github.com/jharmison-redhat/modelcar-maker" \
    model.name="RedHatAI/Voxtral-Mini-3B-2507-FP8-dynamic" \
    model.commit="ce4208e0b3b5f0b46f1e62e9d18c3b244da78975"