{{- with .Values.modelcar.dockerConfigJson }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "modelcar-maker.fullname" $ }}-push
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "modelcar-maker.labels" $ | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ . | b64enc }}
{{- end }}
