{{- if .Values.huggingFace.token }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "modelcar-maker.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "modelcar-maker.labels" $ | nindent 4 }}
type: Opaque
data:
  HF_TOKEN: {{ b64enc .Values.huggingFace.token }}
{{- end }}
