{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "modelcar-maker.serviceAccountName" . }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "modelcar-maker.labels" $ | nindent 4 }}
{{- end }}
