FROM registry.access.redhat.com/ubi9/ubi-minimal:latest


COPY README.md /models/
COPY chat_template.jinja /models/
COPY config.json /models/
COPY configuration_nemotron_h.py /models/
COPY generation_config.json /models/
COPY model-00001-of-00003.safetensors /models/
COPY model-00002-of-00003.safetensors /models/
COPY model-00003-of-00003.safetensors /models/
COPY model.safetensors.index.json /models/
COPY modeling_nemotron_h.py /models/
COPY recipe.yaml /models/
COPY special_tokens_map.json /models/
COPY tokenizer.json /models/
COPY tokenizer_config.json /models/

COPY README.md /modelcard.md

LABEL \
    name=redhatai--nvidia-nemotron-nano-9b-v2-fp8-dynamic-modelcar \
    io.k8s.display-name=redhatai--nvidia-nemotron-nano-9b-v2-fp8-dynamic-modelcar \
    description="A very small RHEL image which contains the contents of huggingface.co/RedHatAI/NVIDIA-Nemotron-Nano-9B-v2-FP8-dynamic downloaded to /models" \
    io.k8s.description="A very small RHEL image which contains the contents of huggingface.co/RedHatAI/NVIDIA-Nemotron-Nano-9B-v2-FP8-dynamic downloaded to /models" \
    maintainer="James Harmison <jharmiso@redhat.com>" \
    release=1 \
    summary="RedHatAI/NVIDIA-Nemotron-Nano-9B-v2-FP8-dynamic model car image" \
    url="https://github.com/jharmison-redhat/modelcar-maker" \
    model.name="RedHatAI/NVIDIA-Nemotron-Nano-9B-v2-FP8-dynamic" \
    model.commit="32a3147d8be0a11a89dec1ce46e9fa12b2f2a9da"