FROM registry.access.redhat.com/ubi9/ubi-minimal:latest


COPY README.md /models/
COPY added_tokens.json /models/
COPY config.json /models/
COPY generation_config.json /models/
COPY merges.txt /models/
COPY model-00001-of-00002.safetensors /models/
COPY model-00002-of-00002.safetensors /models/
COPY model.safetensors.index.json /models/
COPY recipe.yaml /models/
COPY special_tokens_map.json /models/
COPY tokenizer.json /models/
COPY tokenizer_config.json /models/
COPY vocab.json /models/

COPY README.md /modelcard.md

LABEL \
    name=redhatai--granite-3_1-8b-instruct-quantized_w8a8-modelcar \
    io.k8s.display-name=redhatai--granite-3_1-8b-instruct-quantized_w8a8-modelcar \
    description="A very small RHEL image which contains the contents of huggingface.co/RedHatAI/granite-3.1-8b-instruct-quantized.w8a8 downloaded to /models" \
    io.k8s.description="A very small RHEL image which contains the contents of huggingface.co/RedHatAI/granite-3.1-8b-instruct-quantized.w8a8 downloaded to /models" \
    maintainer="James Harmison <jharmiso@redhat.com>" \
    release=1 \
    summary="RedHatAI/granite-3.1-8b-instruct-quantized.w8a8 model car image" \
    url="https://github.com/jharmison-redhat/modelcar-maker" \
    model.name="RedHatAI/granite-3.1-8b-instruct-quantized.w8a8" \
    model.commit="ad22f3810eef979d1bf12daa52a903a16222c5e1"