name: Build & Publish Helm Chart (main branch)

on:
  push:
    paths:
      - "charts/**"
      - .github/workflows/chart.yml

permissions: {}

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Set up Helm
        uses: azure/setup-helm@v4
      - name: Log in to GHCR
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | helm registry login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Package Helm Chart
        run: |
          while read -rd $'\0' chart; do
            name="$(basename "$chart")"
            version="$(awk '/^version:/{print $2}' "$chart/Chart.yaml")"
            before_sha="${{ github.event.before }}"
            if git show "$before_sha:$chart/Chart.yaml"; then
              echo "found old chart in $before_sha"
              old_version="$(git show "$before_sha:$chart/Chart.yaml" | awk '/^version:/{print $2}')"
            else
              echo "no old chart"
              old_version=""
            fi
            echo "$name: $version (old: $old_version)"
          done < <(find charts -type d -mindepth 1 -maxdepth 1 -print0)
          ls -halF charts
