FROM registry.access.redhat.com/ubi9/ubi-minimal:latest


COPY LICENSE /models/
COPY README.md /models/
COPY config.json /models/
COPY generation_config.json /models/
COPY merges.txt /models/
COPY model-00001-of-00002.safetensors /models/
COPY model-00002-of-00002.safetensors /models/
COPY model.safetensors.index.json /models/
COPY tokenizer.json /models/
COPY tokenizer_config.json /models/
COPY vocab.json /models/

COPY README.md /modelcard.md

LABEL \
    name=qwen--qwen3-8b-fp8-modelcar \
    io.k8s.display-name=qwen--qwen3-8b-fp8-modelcar \
    description="A very small RHEL image which contains the contents of huggingface.co/Qwen/Qwen3-8B-FP8 downloaded to /models" \
    io.k8s.description="A very small RHEL image which contains the contents of huggingface.co/Qwen/Qwen3-8B-FP8 downloaded to /models" \
    maintainer="James Harmison <jharmiso@redhat.com>" \
    release=1 \
    summary="Qwen/Qwen3-8B-FP8 model car image" \
    url="https://github.com/jharmison-redhat/modelcar-maker" \
    model.name="Qwen/Qwen3-8B-FP8" \
    model.commit="220b46e3b2180893580a4454f21f22d3ebb187d3"